language: java
jdk:
  - oraclejdk8

before_install:
  - mysql -e 'CREATE DATABASE shbackend_test;'

before_script:
  - "set -e"
script:
  - "mvn test"
  - if [ $TRAVIS_BRANCH = 'develop' ]; then mvn heroku:deploy; fi